### ISSUE TITLE
CPU Core 0 Panic: AppleSPUFirmwareService: firmware validation failed 2

### ISSUE THREAD

**Issue by shenhuanchao** [dualra1n/dualra1n#68]
I was trying to dualboot into iPadOS 14.2 from my main OS of 14.1. Previously I was having the "could not connect to device" error, but I was able to bypass it by changing "./sshrd.sh 15.6" in the dualboot.sh file into "./sshrd.sh 14.1". Now on my Mac's terminal, it successfully goes through all of the steps all the way to booting. However, my iPad Pro 10.5 fails to actually boot in the second OS. So far I've tried iPadOS 14.0, 14.2 and 15.4.1, all result in the same core 0 panic error. I'm wondering if it's something I've done wrong, or if it's a device-specific issue, or if the script is not meant to be used with devices on 14.X. The logs and error messages are in the attached file. Any advice would be much appreciated!
![IMG_1025](https://github.com/dualra1n/dualra1n/assets/47488878/4db9758b-438d-4aac-914f-36a62d5e4cba)
[Dualra1n Log.txt](https://github.com/dualra1n/dualra1n/files/11778622/Dualra1n.Log.txt)

**Comment by shenhuanchao** [comment]
Update: the ios13 branch worked as is, with which I successfully downgraded to iPadOS 13.7. Gyroscope doesn't seem to work though.
I wonder what's the cause of such difference in behavior. Is iOS 14.1 not compatible with other 14.X versions?

**Comment by edwin170** [comment]
> Update: the ios13 branch worked as is, with which I successfully downgraded to iPadOS 13.7. Gyroscope doesn't seem to work though. I wonder what's the cause of such difference in behavior. Is iOS 14.1 not compatible with other 14.X versions?

firstly, on ios 13.7 the gyroscope wasn't working because you didn't put the --fixHard agument. secondly, seems like on ios 14.1 on ipad the path to jump the validation error doesn't work, sadly i don't have that device to check if that's the problem, but you can open the dualboot.sh file and edit the line 1060 which is '"$dir"/Kernel64Patcher work/kcache.patched work/kcache.patchedB -a -b -e `if [ "$fixBoot" = "1" ]; then echo "-s"; fi` `if [ "$fixHard" = "0" ]; then echo "-f"; fi`' to '"$dir"/Kernel64Patcher work/kcache.patched work/kcache.patchedB -a -f -e `if [ "$fixBoot" = "1" ]; then echo "-s"; fi` `if [ "$fixHard" = "0" ]; then echo "-f"; fi`'. you see i just change the -b to -f. ofc you won't have most of the firmware working like giroscope, microphone, etc. so you can try ios 13.7 adding --fixHard in the argument or try edit the line on the main branch. good luck :)

**Comment by shenhuanchao** [comment]
Thank you so much for the reply, much appreciated! I'm gonna try out --fixHard and report back later. 

I was trying to check if my broken front camera functionality was caused by a faulty camera, faulty firmware or faulty motherboard. I ruled out the first by trying multiple replacement cameras. Thanks to Dualra1n, I managed to rule out the second possibility. Now it appears that it's a motherboard issue and sadly there ain't no way I can fix it myself😂.

**Comment by edwin170** [comment]
> Thank you so much for the reply, much appreciated! I'm gonna try out --fixHard and report back later.
> 
> I was trying to check if my broken front camera functionality was caused by a faulty camera, faulty firmware or faulty motherboard. I ruled out the first by trying multiple replacement cameras. Thanks to Dualra1n, I managed to rule out the second possibility. Now it appears that it's a motherboard issue and sadly there ain't no way I can fix it myself😂.

haha sad, hope it will be fixed :)
