### ISSUE TITLE
frozen on : you have the kernelpath already installed, Omitting ...

### ISSUE THREAD

**Issue by LegacyIOS-RU** [dualra1n/dualra1n#98]
[*] Fixed firmwares suscessfully
IOS 13 dualboot or bootx option detected, we are going to use the bootx boot process
[*] Adding the new modified boot images: kernelcache, root_hash, StaticTrustCache, devicetree... 
[*] Copying the new boot images to work with
dtre
[*] Patching kernel ...
[*] If this fails, please run python3 -m pip uninstall lzss, and re-run the script
[*] Checking if a jailbreak is installed
[*] ios 13 detected so we will be automatically installing a jailbreak
[*] Jailbreak detected
[-] you have the kernelpath already installed, Omitting ...
scp: /mnt8/System/Library/Caches/com.apple.kernelcaches/kcache.patched: No such file or directory

**Comment by LegacyIOS-RU** [comment]
ios 13.7,iphone 6s plus

**Comment by mrgarbagegamer** [comment]
Check the discord server if you can for some help but provided you're running on Linux, do the following:

`git pull`
`git checkout kerneldiff`
`sudo ./dualboot.sh --dualboot <ios-version> --dont-create-part --bootx` (if you've already attempted and haven't run restorerootfs)
`sudo ./dualboot.sh --dualboot <ios-version> --bootx` (run this otherwise)

**Comment by edwin170** [comment]
this error was fixed a long time ago soo you just update to lastest if someone read this
